name: Build PDF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile LaTeX
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Compile Satzung.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: satzung.tex
      - name: Compile Beitragsordnung.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: beitragsordnung.tex
      - uses: actions/upload-artifact@master
        with:
          name: Satzung
          path: "*.pdf"
